In [1]:
import pandas as pd
import numpy as np

In [12]:
fake=pd.read_csv('data.csv')

In [11]:
fake.head()

AttributeError: 'function' object has no attribute 'head'

In [13]:
fake=fake.drop(['URLs'],axis=1)
fake=fake.dropna()

In [14]:
fake.head()

Headline  \
0         Four ways Bob Corker skewered Donald Trump   
1  Linklater's war veteran comedy speaks to moder...   
2  Trump’s Fight With Corker Jeopardizes His Legi...   
3  Egypt's Cheiron wins tie-up with Pemex for Mex...   
4        Jason Aldean opens 'SNL' with Vegas tribute   

                                                Body  Label  
0  Image copyright Getty Images\nOn Sunday mornin...      1  
1  LONDON (Reuters) - “Last Flag Flying”, a comed...      1  
2  The feud broke into public view last week when...      1  
3  MEXICO CITY (Reuters) - Egypt’s Cheiron Holdin...      1  
4  Country singer Jason Aldean, who was performin...      1

In [15]:
fake=fake[0:1000]

In [16]:
x=fake.iloc[:,:-1].values #independent variable
y=fake.iloc[:,-1].values #dependent variable

In [17]:
x[0]

array(['Four ways Bob Corker skewered Donald Trump',
       'Image copyright Getty Images\nOn Sunday morning, Donald Trump went off on a Twitter tirade against a member of his own party.\nThis, in itself, isn\'t exactly huge news. It\'s far from the first time the president has turned his rhetorical cannons on his own ranks.\nThis time, however, his attacks were particularly biting and personal. He essentially called Tennessee Senator Bob Corker, the chair of the powerful Senate Foreign Relations Committee, a coward for not running for re-election.\nHe said Mr Corker "begged" for the president\'s endorsement, which he refused to give. He wrongly claimed that Mr Corker\'s support of the Iranian nuclear agreement was his only political accomplishment.\nUnlike some of his colleagues, Mr Corker - free from having to worry about his immediate political future - didn\'t hold his tongue.\nSkip Twitter post by @SenBobCorker It\'s a shame the White House has become an adult day care center. Som

In [18]:
y[0]

1

In [22]:
from sklearn.feature_extraction.text import CountVectorizer #to convert into numerical values
cv=CountVectorizer(max_features=5000) #maximum features to vectorize all text data
mat_body=cv.fit_transform(x[:,1]).todense()

In [20]:
mat_body

matrix([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [21]:
cv_head=CountVectorizer(max_features=5000)
mat_head=cv_head.fit_transform(x[:,0]).todense()

In [23]:
mat_head

matrix([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [31]:
X_mat=np.hstack((mat_head, mat_body)) #stacking head on the top of the body

In [30]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X_mat, y, test_size=0.2, random_state=0)

In [34]:
from sklearn.tree import DecisionTreeClassifier
dtc=DecisionTreeClassifier(criterion='entropy')
dtc.fit(X_train, y_train)
y_pred=dtc.predict(X_test)

In [36]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred) #right diagnol-incorrectly predicted results
#left diagnol-correctly predicted results

array([[96, 10],
       [10, 84]], dtype=int64)

In [37]:
(96+84)/(96+84+10)

0.9473684210526315